refactor: update cached identity if lost
arcxmoney/analytics-sdk pull request #133
Opened 2023-03-14 11:57 UTC by xitronix

Closes #132

2023-03-14 14:10 UTC, gtupak requested changes
The identity is indeed removed but requires a refresh. The second websockets connection still uses the old identity. See the recording below:

https://user-images.githubusercontent.com/5834876/225027857-2cb44f18-68f6-4393-b821-6737104c4574.mov

2023-03-14 18:09 UTC, gtupak requested changes

2023-03-14 18:09 UTC, gtupak commented on src/ArcxAnalyticsSdk.ts
> +      if (error.name === 'InternalServerError') {
Also, realized that in prod it's not an `InternalServerError` but rather a `BadRequestError`. See here: 

![image](https://user-images.githubusercontent.com/5834876/225098304-8a7d0467-78cf-477a-8f10-cc3a951a739e.png)

Identity ID: `32198a83d76a6993e501f643`

2023-03-15 10:57 UTC, xitronix commented
https://user-images.githubusercontent.com/18648454/225289024-abcba570-3708-4645-b55f-30f8f01f8a39.mov

2023-03-15 12:22 UTC, gtupak approved these changes

2023-03-15 12:22 UTC, merged

2023-03-15 13:58 UTC, gtupak commented
:tada: This PR is included in version 1.8.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@arcxmoney/analytics/v/1.8.2)
- [GitHub release](https://github.com/arcxmoney/analytics-sdk/releases/tag/v1.8.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: